---
- name: Ensure lib directory exists
  file: path={{ ct_libs_base_path }} state=directory mode=0755

- name: Ensure each lib directory exists
  file: path={{ item.path }} state=directory mode=0755
  with_items: ct_libs

- name: fetch release info
  uri: url="https://api.github.com/repos/basho/riak-{{ item.path }}-client/releases/latest" return_content=yes
  register: "release_data"
  with_items: ct_libs

- name: fetch client archives
  unarchive: src={{ (item.content|from_json)['tarball_url'] }} dest={{ ct_libs[item.index].path }} copy=no
  with_items: release_data

- name:
