- src: 'azmodude.pyenv'
- src: 'basho-labs.riak-kv'
- src: 'gantsign.maven'
- src: 'geerlingguy.composer'
- src: 'geerlingguy.php'
- src: 'geerlingguy.repo-remi'
- src: 'geerlingguy.ruby'
- src: 'joshualund.golang'
- src: 'williamyeh.oracle-java'
