---
- name: Include RHEL vars
  include_vars: RedHat.yml
  tags: RedHat

- name: "Install Java & libselinux-python"
  package: "name={{ item }} state=present"
  tags: RedHat
  with_items:
    - java-1.7.0-openjdk
    - libselinux-python
