---
- name: install unzip
  yum: name=unzip state=present

- name: check jenv exists
  stat: path=~/.jenv/bin/jenv-init.sh
  register: jenv_init
  sudo: false

- name: Install jenv
  command: curl -L -s get.jenv.io | bash
  when: not jenv_init.stat.exists

- name: Install java
  command: jenv install java {{ java_version }}

- name: Set default java candidate
  command: jenv default java {{ java_default }}

- name: Set/verify java home in .bashrc
  lineinfile: dest=~/.bashrc regexp='^export JAVA_HOME' line='export JAVA_HOME=$HOME/.jenv/candidates/java/current/'

- name: Install maven
  command: jenv install maven {{ java_maven_version }}
  when: java_maven_version
