---
- name: ensure a bash_profile file exists for user
  file: "dest=~{{ basho_user | default(ansible_ssh_user) }}/.bash_profile state=touch"
  become: false

- name: Set GOPATH
  lineinfile: "dest=~{{ basho_user | default(ansible_ssh_user) }}/.bash_profile line='export GOPATH=$GOPATH:{{ golang_gopath }}'"
  become: false

- name: symlink go to /usr/bin making it available to ansible
  file: "src=/usr/local/go/bin/go dest=/usr/bin/go state=link mode={{ golang_usr_bin_mode }}"
  when: golang_usr_bin
