---
- name: Set PYENV_ROOT
  lineinfile: "dest={{ lookup('env','HOME') }}/.bash_profile line='export PYENV_ROOT={{ pyenv_root }}'"
  become: false

- name: Add pyenv to path
  lineinfile: "dest={{ lookup('env','HOME') }}/.bash_profile line='export PATH=$PYENV_ROOT/bin:$PATH'"
  become: false

- name: Add pyenv init to bash_profile
  lineinfile: "dest={{ lookup('env','HOME') }}/.bash_profile line='eval \"$(pyenv init -)\"'"
  become: false

- name: check for python
  command: "{{ pyenv_root }}/bin/pyenv versions"
  become: false
  register: pyenv_versions_output

- name: install python
  command: "{{ pyenv_root }}/bin/pyenv install {{ python_version }}"
  become: false
  when: python_version not in pyenv_versions_output.stdout
